### PR TITLE
Add support for deleting environments

### PR DESCRIPTION
**Pull request by WhatsARanjit**

### CODE REVIEW

**Comment by briancain** [comment]
Hey @WhatsARanjit, thanks for the pull request! Is this a new feature of the environments endpoint for a future PE release? I don't see this as a valid operation on the environments endpoint in the [classifier latest docs](https://docs.puppetlabs.com/pe/latest/nc_environments.html)

**Comment by briancain** [comment]
ping @WhatsARanjit

**Comment by WhatsARanjit** [comment]
Sorry for the delay.  In the meantime, I've added a method to prosvcs-node_manager (which is built upon puppetclassify) and it successfully is able to delete environments.

https://github.com/puppetlabs/prosvcs-node_manager/blob/master/lib/puppet/util/node_groups.rb#L57-L68

```
[master ~]# puppet resource puppet_environment test
puppet_environment { 'test':
  ensure => 'absent',
}
[master ~]# puppet resource puppet_environment test ensure=present
Notice: /Puppet_environment[test]/ensure: created
puppet_environment { 'test':
  ensure => 'present',
}
[master ~]# puppet resource puppet_environment test
puppet_environment { 'test':
  ensure => 'present',
}
[master ~]# puppet resource puppet_environment test ensure=absent
Notice: /Puppet_environment[test]/ensure: removed
puppet_environment { 'test':
  ensure => 'absent',
}
[master ~]# puppet resource puppet_environment test
puppet_environment { 'test':
  ensure => 'absent',
}
```

**Comment by briancain** [comment]
Ah, fair enough. I guess my worry here is adding some functionality that isn't supported, at least according to the [classifier documentation](https://docs.puppetlabs.com/pe/latest/nc_environments.html). @aperiodic any opinions on this? It looks like it's a route that exists on the environments endpoint, but if I'm reading the code right, I think it just deletes the environment from the database?

**Comment by WhatsARanjit** [comment]
@briancain, yea actually none of the operations do anything but update the database.  It doesn't actually create anything on disk.

**Comment by binford2k** [comment]
@jonathannewman hey, any thoughts about revisiting this PR? Looks like you & @jessereynolds are the top committers on this project now.

https://puppet.com/docs/puppetserver/6.2/admin-api/v1/environment-cache.html is probably the API we'd want to use now.

**Comment by binford2k** [comment]
Actually, the admin api probably doesn't belong in here. I'll build a new tool that uses the puppetclassify https layer to talk to the puppet server. I don't know about the environment delete api though.

**Comment by WhatsARanjit** [comment]
Just for posterity, `WhatsARanjit/node_manager` no longer uses `puppet-classify`.

**Comment by jonathannewman** [comment]
@WhatsARanjit any objection to closing this?

**Comment by WhatsARanjit** [comment]
@jonathannewman Can be closed from my perspective.

**Comment by jonathannewman** [comment]
Thanks!

**Pull request closed without merging**
